# fly.toml app configuration file generated for sora-backend on 2026-05-21T10:36:02-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'sora-backend'
primary_region = 'gru'

[build]

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpus = 1
  memory_mb = 256
